name: Sync develop from 2025-source-code

on:
  push:
    branches:
      - 2025-source-code

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 2025-source-code
          fetch-depth: 0

      - name: Push to develop
        run: git push origin 2025-source-code:develop --force
